parameters:
    # empty param to be set by
    allegro_sites.format.urls: ~

services:
    allegro_sites.listener.CRUD:
        class: Allegro\SitesBundle\Listener\CRUDListener
        # circular reference if sending @security.context
        arguments: [ @service_container ]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: onFlush }
            - { name: doctrine.event_listener, event: postLoad }

    # For automatic management of lang in session
    allegro_sites.listener.session:
        class: Allegro\SitesBundle\Listener\SessionListener
        arguments: [ %kernel.default_locale% ]
        tags:
            - { name: kernel.event_subscriber }

    allegro_sites.helper.routing:
        class: Allegro\SitesBundle\Util\RoutingHelper
        arguments: [ @router, @session, @doctrine.orm.entity_manager, %allegro_sites.format.urls%, %kernel.default_locale% ]

    allegro_sites.twig.extension:
        class: Allegro\SitesBundle\Twig\Extension\AllegroSitesExtension
        # circular reference if sending don't remember which [ @templating, @session ]
        arguments: [ @allegro_sites.helper.routing, @service_container ]
        tags:
            - { name: twig.extension }

    #~ trd_party.twig.extension:
        #~ class: Allegro\SitesBundle\Twig\Extension\EvaluateExtension
        #~ arguments: [ @service_container ]
        #~ tags:
            #~ - { name: twig.extension }

    allegro_sites.form.type.info:
        class: Allegro\SitesBundle\Form\StaticTextType
        tags:
            - { name: form.type, alias: allg_static_text }

    allegro_sites.form.type.collection_info:
        class: Allegro\SitesBundle\Form\SiteTreeType
        tags:
            - { name: form.type, alias: allg_site_tree }

    allegro_sites.form.type.link:
        class: Allegro\SitesBundle\Form\StaticLinkType
        tags:
            - { name: form.type, alias: allg_static_link }
